---
get:
  tags:
    - APIInfo
  summary: Get describing html of openapi spec
  description: Retrieve the OpenAPI spec as HTML
  operationId: getOpenAPIHTML
  responses:
    "200":
      description: The rendered HTML for the OpenAPI spec
      content:
        text/html:
          schema:
            type: string
            example: "<html>...</html>"
    "400":
      description: The OpenAPI HTML request was malformed
      content:
        application/problem+json:
          schema:
            $ref: "../../schemas/_index.yml#/ProblemDetails"

  # This API has no security
  security: []
