---
get:
  tags:
    - APIInfo
  summary: Get openapi spec as json
  description: Retrieve the OpenAPI spec as JSON
  operationId: getOpenAPIJSON
  responses:
    "200":
      description: The OpenAPI spec as JSON
      content:
        application/json:
          schema:
            type: object
          example: {}
    "400":
      description: The OpenAPI request was malformed
      content:
        application/problem+json:
          schema:
            $ref: "../../schemas/_index.yml#/ProblemDetails"

  # This API has no security
  security: []
